export type Video = {
  id: string;
  title: string;
  channel: string;
  viewCount: string;
  uploadTime: string;
  duration: string;
  description: string;
  thumbnail: string;
  tags: string[];
};

export const videos: Video[] = [
  {
    id: "v1",
    title: "20 Min Beginner Full Body Strength",
    channel: "Fitness Channel",
    viewCount: "1.2M views",
    uploadTime: "2 weeks ago",
    duration: "20:15",
    description: "Beginner friendly full body strength workout with dumbbells.",
    thumbnail: "/thumbnail1.jpg",
    tags: ["beginner", "strength", "dumbbells", "20-30min"],
  },
  {
    id: "v2",
    title: "15 Min No Equipment Cardio",
    channel: "Fitness Channel",
    viewCount: "900K views",
    uploadTime: "1 month ago",
    duration: "15:00",
    description:
      "Quick cardio workout you can do at home, no equipment needed.",
    thumbnail: "/thumbnail2.jpg",
    tags: ["beginner", "cardio", "no-equipment", "<20min"],
  },
  {
    id: "v3",
    title: "30 Min Intermediate HIIT Workout",
    channel: "Fitness Channel",
    viewCount: "800K views",
    uploadTime: "3 weeks ago",
    duration: "30:00",
    description: "High intensity HIIT workout for intermediate level.",
    thumbnail: "/thumbnail3.jpg",
    tags: ["intermediate", "hiit", "no-equipment", "30-60min"],
  },
  {
    id: "v4",
    title: "45 Min Strength Training with Dumbbells",
    channel: "Fitness Channel",
    viewCount: "1M views",
    uploadTime: "1 week ago",
    duration: "45:00",
    description: "Intermediate strength workout focusing on upper body.",
    thumbnail: "/thumbnail1.jpg",
    tags: ["intermediate", "strength", "dumbbells", "30-60min"],
  },
  {
    id: "v5",
    title: "60 Min Advanced Full Body Strength",
    channel: "Fitness Channel",
    viewCount: "1.5M views",
    uploadTime: "2 days ago",
    duration: "60:00",
    description: "Advanced level full body workout using dumbbells.",
    thumbnail: "/thumbnail2.jpg",
    tags: ["advanced", "strength", "dumbbells", "60+min"],
  },
  {
    id: "v6",
    title: "25 Min Beginner Yoga Flow",
    channel: "Fitness Channel",
    viewCount: "700K views",
    uploadTime: "4 weeks ago",
    duration: "25:00",
    description: "Gentle yoga flow perfect for beginners.",
    thumbnail: "/thumbnail3.jpg",
    tags: ["beginner", "yoga", "flexibility", "20-30min"],
  },
  {
    id: "v7",
    title: "40 Min Intermediate Yoga for Flexibility",
    channel: "Fitness Channel",
    viewCount: "850K views",
    uploadTime: "1 week ago",
    duration: "40:00",
    description: "Yoga session to improve flexibility and mobility.",
    thumbnail: "/thumbnail1.jpg",
    tags: ["intermediate", "yoga", "flexibility", "30-60min"],
  },
  {
    id: "v8",
    title: "10 Min Morning Stretch",
    channel: "Fitness Channel",
    viewCount: "500K views",
    uploadTime: "5 days ago",
    duration: "10:00",
    description: "Short stretching routine to start your day.",
    thumbnail: "/thumbnail2.jpg",
    tags: ["beginner", "flexibility", "no-equipment", "<20min"],
  },
  {
    id: "v9",
    title: "30 Min Cardio + Strength Combo",
    channel: "Fitness Channel",
    viewCount: "1.3M views",
    uploadTime: "3 days ago",
    duration: "30:00",
    description: "Combination workout with cardio and strength elements.",
    thumbnail: "/thumbnail3.jpg",
    tags: ["intermediate", "cardio", "strength", "no-equipment", "30-60min"],
  },
  {
    id: "v10",
    title: "20 Min Beginner Dumbbell Arms",
    channel: "Fitness Channel",
    viewCount: "600K views",
    uploadTime: "2 weeks ago",
    duration: "20:00",
    description: "Beginner dumbbell workout focused on arms.",
    thumbnail: "/thumbnail1.jpg",
    tags: ["beginner", "strength", "dumbbells", "20-30min"],
  },
  {
    id: "v11",
    title: "35 Min HIIT Cardio Blast",
    channel: "Fitness Channel",
    viewCount: "1.1M views",
    uploadTime: "4 days ago",
    duration: "35:00",
    description: "Sweaty HIIT cardio workout for intermediate level.",
    thumbnail: "/thumbnail2.jpg",
    tags: ["intermediate", "hiit", "cardio", "no-equipment", "30-60min"],
  },
  {
    id: "v12",
    title: "50 Min Advanced Strength Training",
    channel: "Fitness Channel",
    viewCount: "1.4M views",
    uploadTime: "1 day ago",
    duration: "50:00",
    description: "Advanced strength workout using dumbbells.",
    thumbnail: "/thumbnail3.jpg",
    tags: ["advanced", "strength", "dumbbells", "30-60min"],
  },
];
