export type Video = {
  youtubeId: string;
  title: string;
  channel: string;
  viewCount: number;
  publishedAt: string;
  durationSec: number;
  description: string;
  thumbnail: string;
  tags: string[];
};

// export const videos: Video[] = [
//   {
//     youtubeId: "v1",
//     title: "20 Min Beginner Full Body Strength",
//     channel: "Fitness Channel",
//     viewCount: "1.2M views",
//     uploadTime: "2 weeks ago",
//     duration: "20:15",
//     description: "Beginner friendly full body strength workout.",
//     thumbnail: "/thumbnail1.jpg",
//     tags: ["beginner", "strength"],
//   },
//   {
//     youtubeId: "v2",
//     title: "15 Min No Equipment Cardio",
//     channel: "Fitness Channel",
//     viewCount: "900K views",
//     uploadTime: "1 month ago",
//     duration: "15:00",
//     description: "Quick beginner cardio workout at home.",
//     thumbnail: "/thumbnail2.jpg",
//     tags: ["beginner", "cardio"],
//   },
//   {
//     youtubeId: "v3",
//     title: "30 Min Intermediate HIIT Workout",
//     channel: "Fitness Channel",
//     viewCount: "800K views",
//     uploadTime: "3 weeks ago",
//     duration: "30:00",
//     description: "High intensity HIIT workout for intermediate level.",
//     thumbnail: "/thumbnail3.jpg",
//     tags: ["intermediate", "hiit"],
//   },
//   {
//     youtubeId: "v4",
//     title: "45 Min Strength Training",
//     channel: "Fitness Channel",
//     viewCount: "1M views",
//     uploadTime: "1 week ago",
//     duration: "45:00",
//     description: "Intermediate strength workout focusing on upper body.",
//     thumbnail: "/thumbnail1.jpg",
//     tags: ["intermediate", "strength"],
//   },
//   {
//     youtubeId: "v5",
//     title: "60 Min Advanced Full Body Strength",
//     channel: "Fitness Channel",
//     viewCount: "1.5M views",
//     uploadTime: "2 days ago",
//     duration: "60:00",
//     description: "Advanced full body strength workout.",
//     thumbnail: "/thumbnail2.jpg",
//     tags: ["advanced", "strength"],
//   },
//   {
//     youtubeId: "v6",
//     title: "25 Min Beginner Yoga Flow",
//     channel: "Fitness Channel",
//     viewCount: "700K views",
//     uploadTime: "4 weeks ago",
//     duration: "25:00",
//     description: "Gentle yoga flow perfect for beginners.",
//     thumbnail: "/thumbnail3.jpg",
//     tags: ["beginner", "yoga"],
//   },
//   {
//     youtubeId: "v7",
//     title: "40 Min Intermediate Yoga Flow",
//     channel: "Fitness Channel",
//     viewCount: "850K views",
//     uploadTime: "1 week ago",
//     duration: "40:00",
//     description: "Yoga session to improve mobility.",
//     thumbnail: "/thumbnail1.jpg",
//     tags: ["intermediate", "yoga"],
//   },
//   {
//     youtubeId: "v8",
//     title: "10 Min Morning Stretch",
//     channel: "Fitness Channel",
//     viewCount: "500K views",
//     uploadTime: "5 days ago",
//     duration: "10:00",
//     description: "Short stretching routine to start your day.",
//     thumbnail: "/thumbnail2.jpg",
//     tags: ["beginner", "stretching"],
//   },
//   {
//     youtubeId: "v9",
//     title: "30 Min Cardio + Strength Combo",
//     channel: "Fitness Channel",
//     viewCount: "1.3M views",
//     uploadTime: "3 days ago",
//     duration: "30:00",
//     description: "Combination workout with cardio and strength.",
//     thumbnail: "/thumbnail3.jpg",
//     tags: ["intermediate", "cardio", "strength"],
//   },
//   {
//     youtubeId: "v10",
//     title: "20 Min Beginner Strength Arms",
//     channel: "Fitness Channel",
//     viewCount: "600K views",
//     uploadTime: "2 weeks ago",
//     duration: "20:00",
//     description: "Beginner strength workout focused on arms.",
//     thumbnail: "/thumbnail1.jpg",
//     tags: ["beginner", "strength"],
//   },
//   {
//     youtubeId: "v11",
//     title: "35 Min HIIT Cardio Blast",
//     channel: "Fitness Channel",
//     viewCount: "1.1M views",
//     uploadTime: "4 days ago",
//     duration: "35:00",
//     description: "Sweaty HIIT cardio workout.",
//     thumbnail: "/thumbnail2.jpg",
//     tags: ["intermediate", "hiit", "cardio"],
//   },
//   {
//     youtubeId: "v12",
//     title: "50 Min Advanced Strength Training",
//     channel: "Fitness Channel",
//     viewCount: "1.4M views",
//     uploadTime: "1 day ago",
//     duration: "50:00",
//     description: "Advanced strength workout.",
//     thumbnail: "/thumbnail3.jpg",
//     tags: ["advanced", "strength"],
//   },
// ];
