import { NextResponse } from "next/server";
import fs from "node:fs/promises";
import path from "node:path";

// This API route serves the cached videos data from a local JSON file.
// The data is generated by the seed script and stored in app/lib/videos-cache.json.
// This approach avoids hitting the YouTube API on every request and allows for faster responses.
export async function GET() {
  const filePath = path.join(process.cwd(), "app", "lib", "videos-cache.json");
  const raw = await fs.readFile(filePath, "utf-8");
  const data = JSON.parse(raw);
  return NextResponse.json(data);
}
